# Generated by Django 4.2 on 2023-05-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0005_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
