# Generated by Django 4.2 on 2023-05-10 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_rental', '0012_delete_vehicleassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reassigned_at', models.DateTimeField(auto_now_add=True)),
                ('reassigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignments', to=settings.AUTH_USER_MODEL)),
                ('rental_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental.rentalrequest')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental.vehicle')),
            ],
        ),
    ]
