# Generated by Django 4.2 on 2023-05-10 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0014_alter_rating_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='car_rental.vehicle'),
        ),
    ]
