# Generated by Django 4.2.1 on 2023-05-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0016_remove_rentalreturn_user_complaint_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
