# Generated by Django 4.2.1 on 2023-05-23 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0018_complaint_rental_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='rental_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_rental.rentalrequest'),
        ),
    ]
