# Generated by Django 4.2.1 on 2023-05-25 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0020_remove_complaint_rental_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car_rental.vehicle'),
        ),
    ]
