# Generated by Django 4.2.1 on 2023-05-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0021_alter_complaint_vehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='rentalreturn',
            options={'ordering': ['-id']},
        ),
    ]
